baseURL = "https://aludwar.github.io"
languageCode = "en-us"
title = "Calgary RHCE"
theme = "soho"
publishDir = "aludwar.github.io"

enableInlineShortcodes = true

summarylength = 50
enableEmoji = true

[params]
author = "Andrew Ludwar"
description = "A linux and open source technology blog."
profilePicture = "wp-content/uploads/2016/08/cropped-1477782_10152102853181489_71278912_n.jpg"
themeColor = "#990000"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://ca.linkedin.com/in/andrewludwar"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/aludwar"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/andrewludwar"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
